@TM:1380156015
@A:  :"":0:0:0:-1|premap output is up to date. No run necessary.
@TM:1380156007
@N:  :"":0:0:0:-1|Running in 32-bit mode
@TM:1380156010
@N: MF249 :"":0:0:0:-1|Running in 32-bit mode.
@N: MF667 :"":0:0:0:-1|Clock conversion disabled 
@TM:1380156007
@N: CD720 :"C:\Microsemi\Libero_v11.0\Synopsys\synplify_G201209MSP1\lib\vhd2008\std.vhd":146:18:146:21|M
@N: CD231 :"C:\Microsemi\Libero_v11.0\Synopsys\synplify_G201209MSP1\lib\vhd2008\std1164.vhd":913:16:913:17|M
@N: CD630 :"C:\Users\Aaron\Desktop\fpga2\FPGA\hdl\display.vhd":25:7:25:13|M
@W: CL159 :"C:\Users\Aaron\Desktop\fpga2\FPGA\hdl\display.vhd":32:4:32:7|M
@W: CL159 :"C:\Users\Aaron\Desktop\fpga2\FPGA\hdl\display.vhd":33:4:33:10|M
@W: CL159 :"C:\Users\Aaron\Desktop\fpga2\FPGA\hdl\display.vhd":34:1:34:2|M
@W: CL159 :"C:\Users\Aaron\Desktop\fpga2\FPGA\hdl\display.vhd":39:1:39:5|M
@N: CD231 :"C:\Users\Aaron\Desktop\fpga2\FPGA\hdl\display.vhd":53:12:53:13|M
@W: CD638 :"C:\Users\Aaron\Desktop\fpga2\FPGA\hdl\display.vhd":132:7:132:12|M
@W: CL252 :"C:\Users\Aaron\Desktop\fpga2\FPGA\hdl\display.vhd":132:7:132:12|M
@W: CL169 :"C:\Users\Aaron\Desktop\fpga2\FPGA\hdl\display.vhd":217:1:217:2|M
@N: CL201 :"C:\Users\Aaron\Desktop\fpga2\FPGA\hdl\display.vhd":236:1:236:2|M
@A: CL282 :"C:\Users\Aaron\Desktop\fpga2\FPGA\hdl\display.vhd":236:1:236:2|M
@N: CD630 :"C:\Users\Aaron\Desktop\fpga2\FPGA\hdl\i2c.vhd":35:7:35:9|M
@N: CD231 :"C:\Users\Aaron\Desktop\fpga2\FPGA\hdl\i2c.vhd":59:13:59:14|M
@W: CL169 :"C:\Users\Aaron\Desktop\fpga2\FPGA\hdl\i2c.vhd":86:0:86:1|M
@N: CL201 :"C:\Users\Aaron\Desktop\fpga2\FPGA\hdl\i2c.vhd":86:0:86:1|M
@W: CL279 :"C:\Users\Aaron\Desktop\fpga2\FPGA\hdl\i2c.vhd":86:0:86:1|M
@W: CD604 :"C:\Users\Aaron\Desktop\fpga2\FPGA\hdl\i2c.vhd":416:2:416:15|M
@N:  :"C:\Users\Aaron\Desktop\fpga2\FPGA\hdl\top.vhd":25:7:25:9|M
@N: CD630 :"C:\Users\Aaron\Desktop\fpga2\FPGA\hdl\top.vhd":25:7:25:9|M
@W: CL159 :"C:\Users\Aaron\Desktop\fpga2\FPGA\hdl\top.vhd":33:1:33:3|M
@W: CL159 :"C:\Users\Aaron\Desktop\fpga2\FPGA\hdl\top.vhd":34:4:34:6|M
@W: CD638 :"C:\Users\Aaron\Desktop\fpga2\FPGA\hdl\top.vhd":60:7:60:15|M
@N: CD233 :"C:\Users\Aaron\Desktop\fpga2\FPGA\hdl\top.vhd":65:12:65:13|M
@W: CL111 :"C:\Users\Aaron\Desktop\fpga2\FPGA\hdl\top.vhd":116:0:116:1|M
@W: CL111 :"C:\Users\Aaron\Desktop\fpga2\FPGA\hdl\top.vhd":132:1:132:2|M
@N: CL201 :"C:\Users\Aaron\Desktop\fpga2\FPGA\hdl\top.vhd":132:1:132:2|M
